version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    working_directory: /go/src/github.com/liftbridge-io/liftbridge
    steps:
      - checkout
      - run: apt-get update -yqq && apt-get install -yqq bzr
      - run: GO111MODULE=on go test -v ./...
